// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQk82EZBI1o3pIAwMHB5u4DdGkvtv-ukY',
    appId: '1:927899513191:web:f8f4e8a8dd785b2d64ffc2',
    messagingSenderId: '927899513191',
    projectId: 'instagramkorki',
    authDomain: 'instagramkorki.firebaseapp.com',
    storageBucket: 'instagramkorki.appspot.com',
    measurementId: 'G-406MK21EGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR9db6GiO7wMhAnErRtZOdt_52VKCb3wE',
    appId: '1:927899513191:android:44a2b4e506617c8164ffc2',
    messagingSenderId: '927899513191',
    projectId: 'instagramkorki',
    storageBucket: 'instagramkorki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgTjzCsanawhOaPQqN55H74xPBmMGdUSg',
    appId: '1:927899513191:ios:dcd38a1ee5cc910864ffc2',
    messagingSenderId: '927899513191',
    projectId: 'instagramkorki',
    storageBucket: 'instagramkorki.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgTjzCsanawhOaPQqN55H74xPBmMGdUSg',
    appId: '1:927899513191:ios:3c3fbe12ced7794c64ffc2',
    messagingSenderId: '927899513191',
    projectId: 'instagramkorki',
    storageBucket: 'instagramkorki.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
